### ISSUE TITLE
Incorrect use of ParentDataWidget.

### ISSUE THREAD

**Issue by pedroermarinho** [Flutterando/routefly#15]
Estou tendo esse problema, alguma sugestão de como resolver ?

```dart
class PublicLayout extends StatelessWidget {
  const PublicLayout({super.key});

  @override
  Widget build(BuildContext context) {
    // return   RouterOutlet();
    return YaruMasterDetailPage(
      length: 1,
      appBar: const YaruWindowTitleBar(),
      tileBuilder: (context, index, selected, availableWidth) {
        return YaruMasterTile(
          leading: Icon(YaruIcons.ubuntu_logo),
          title: Text('Home'),
        );
      },
      pageBuilder: (context, index) => YaruDetailPage(
        appBar: YaruWindowTitleBar(
          title: Text('Page 1'),
        ),
        body: Center(
          child: Expanded(child: RouterOutlet(),)
        ),
      ),
    );
  }
}
```
```bash
======== Exception caught by widgets library =======================================================
The following assertion was thrown while applying parent data.:
Incorrect use of ParentDataWidget.

The ParentDataWidget Expanded(flex: 1) wants to apply ParentData of type FlexParentData to a RenderObject, which has been set up to accept ParentData of incompatible type BoxParentData.

Usually, this means that the Expanded widget has the wrong ancestor RenderObjectWidget. Typically, Expanded widgets are placed directly inside Flex widgets.
The offending Expanded is currently placed inside a Center widget.

The ownership chain for the RenderObject that received the incompatible parent data was:
  ErrorWidget-[#3958f] ← Builder ← _RouterScope ← UnmanagedRestorationScope ← Router<RouteEntity> ← RouterOutlet ← Expanded ← Center ← KeyedSubtree-[GlobalKey#8d2d5] ← _BodyBuilder ← ⋯
When the exception was thrown, this was the stack: 
#0      RenderObjectElement._updateParentData.<anonymous closure> (package:flutter/src/widgets/framework.dart:6534:11)
#1      RenderObjectElement._updateParentData (package:flutter/src/widgets/framework.dart:6551:6)
#2      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5856:15)
#3      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#4      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5858:15)
#5      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#6      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5858:15)
#7      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#8      ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5858:15)
#9      ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#10     ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5858:15)
#11     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#12     ParentDataElement._applyParentData.applyParentDataToChild (package:flutter/src/widgets/framework.dart:5858:15)
#13     ComponentElement.visitChildren (package:flutter/src/widgets/framework.dart:5532:14)
#14     ParentDataElement._applyParentData (package:flutter/src/widgets/framework.dart:5861:5)
#15     ParentDataElement.notifyClients (package:flutter/src/widgets/framework.dart:5904:5)
#16     ProxyElement.updated (package:flutter/src/widgets/framework.dart:5819:5)
#17     ProxyElement.update (package:flutter/src/widgets/framework.dart:5808:5)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#19     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#22     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#23     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#24     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#25     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#27     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#30     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#31     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#32     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#33     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#34     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#35     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#37     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973:32)
#38     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#42     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#45     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#46     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#47     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#48     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#50     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#51     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#52     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#53     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#54     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#55     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#56     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#57     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#59     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#60     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#61     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#62     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#63     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#69     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#70     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#72     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#73     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#74     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#77     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#78     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#79     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#80     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#81     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#82     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#83     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#84     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#85     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#86     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#87     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#88     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#89     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#90     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#91     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#92     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#94     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#95     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#96     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#97     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#98     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#99     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#100    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#101    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#102    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#103    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#104    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#105    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#106    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#107    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#108    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#109    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#110    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#111    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#112    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#113    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#114    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#115    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#116    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#117    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#118    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1034:7)
#122    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================

======== Exception caught by widgets library =======================================================
The following _TypeError was thrown building Builder(dirty, dependencies: [_ModalScopeStatus]):
type 'MaterialPage<dynamic>' is not a subtype of type 'RouteflyPage' in type cast

The relevant error-causing widget was: 
  RouterOutlet RouterOutlet:file:///home/pedroermarinho/GitHub/game_tweaks/lib/app/public/public_layout.dart:28:34
When the exception was thrown, this was the stack: 
#0      Routefly.of (package:routefly/src/routefly.dart:49:51)
#1      OutletRouterDelegate.build (package:routefly/src/navigation/outlet/outlet_delegate.dart:36:28)
#2      Builder.build (package:flutter/src/widgets/basic.dart:7698:48)
#3      StatelessElement.build (package:flutter/src/widgets/framework.dart:5550:49)
#4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5480:15)
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#6      StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#7      Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#8      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#10     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#12     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#13     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#14     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#15     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#16     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#17     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#18     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#19     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#20     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#21     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#22     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#23     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#24     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#25     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#26     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#27     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#28     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#29     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#30     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#32     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#33     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#34     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#35     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#36     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#37     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#38     StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#40     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#42     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#43     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#44     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#45     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#46     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#47     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#48     Element.updateChildren (package:flutter/src/widgets/framework.dart:3973:32)
#49     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6918:17)
#50     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#51     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#52     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#53     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#54     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#55     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#56     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#57     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#58     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#59     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#60     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#61     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#62     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#63     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#64     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#66     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#67     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#68     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#69     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#70     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#71     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#72     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#73     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#74     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#75     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#76     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#77     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#78     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#79     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#80     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6765:14)
#81     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#82     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#83     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#84     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#85     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#86     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#87     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#88     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#89     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#90     StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#91     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#92     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#93     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#94     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#95     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#96     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#97     Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#98     ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#99     Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#100    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#101    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#102    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#103    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#104    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#105    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#106    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#107    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#108    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#110    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#111    ProxyElement.update (package:flutter/src/widgets/framework.dart:5809:5)
#112    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#113    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#114    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5643:11)
#115    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#116    StatefulElement.update (package:flutter/src/widgets/framework.dart:5666:5)
#117    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#119    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#120    StatelessElement.update (package:flutter/src/widgets/framework.dart:5556:5)
#121    Element.updateChild (package:flutter/src/widgets/framework.dart:3824:15)
#122    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5505:16)
#123    Element.rebuild (package:flutter/src/widgets/framework.dart:5196:7)
#124    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2904:19)
#125    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:989:21)
#126    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:448:5)
#127    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1386:15)
#128    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1311:9)
#129    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1034:7)
#133    _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
(elided 3 frames from class _Timer and dart:async-patch)
====================================================================================================
Reloaded 1 of 1901 libraries in 377ms (compile: 22 ms, reload: 123 ms, reassemble: 223 ms).
```

**Comment by wendellrocha** [comment]
O expanded é um widget flexível. Você deve colocá-lo dentro de uma row ou de uma column.

**Comment by pedroermarinho** [comment]
Ignore o expanded, coloquei ele só para testar,  mesmo sem ele o segundo ainda erro continua

The following _TypeError was thrown building Builder(dirty, dependencies: [_ModalScopeStatus]):
type 'MaterialPage<dynamic>' is not a subtype of type 'RouteflyPage' in type cast

**Comment by jacobaraujo7** [comment]
Acredito que essa issue não tem a ver com o package, por isso será fechada.
